# Generated by Django 5.1.4 on 2025-07-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_orderproduct_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAndReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя пользователя')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание комментария')),
                ('review_rating', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Рейтинг отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='market.product', verbose_name='Комментарий продукта')),
            ],
            options={
                'verbose_name': 'Комментарий и отзывы продукта',
                'verbose_name_plural': 'Комментарии и отзывы продуктов',
                'ordering': ['-created_at'],
            },
        ),
    ]
