# Generated by Django 5.1.4 on 2025-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_commentandreviewproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Продукт со скидкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Новый продукт'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Популярный продукт'),
        ),
    ]
