# Generated by Django 5.1.4 on 2025-07-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_product_is_discounted_product_is_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=100, verbose_name='Код продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='package_code',
            field=models.CharField(default=1, max_length=100, verbose_name='Код упаковки'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
