# Generated by Django 5.1.4 on 2025-07-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество на складе'),
        ),
    ]
