# Generated by Django 5.1.4 on 2025-07-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='payme_token',
            field=models.TextField(blank=True, null=True, verbose_name='Payme Token'),
        ),
        migrations.AddField(
            model_name='carddetails',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
